### ISSUE TITLE
`connector-restart` exit with exit code 4 when result of jq is empty

### ISSUE THREAD

**Issue by anvaari** [sentoz/kafka-connect-restart#11]
Hi again.
I think It's bug.when `set -euo` set in the script, whenever each command exit with non 0 exit code, script will fail and exit. Also when set `jq` with `e` option, It exit with exit code = 4 when the result is empty. Suppose we haven't any failed connector, so script exit with 4 and it cause the  `CrashLoopBackoff`.
It will be fixed when remove `e` option from `jq`

**Comment by sentoz** [comment]
@anvaari  thank you!)
