### ISSUE TITLE
Service failed, and can't restart connector

### ISSUE THREAD

**Issue by MastyaD** [sentoz/kafka-connect-restart#3]
The service issued such a message log and restarts indefinitely

2021/12/03 13:23:00 [INFO] SIDECAR_MODE=true
2021/12/03 13:23:00 [INFO] KAFKA_CONNECT_HOST=localhost
2021/12/03 13:23:00 [INFO] KAFKA_CONNECT_PORT=8083
2021/12/03 13:23:01 [INFO] REQUEST_DELAY=20
2021/12/03 13:23:01 [INFO] Wait start kafka-connect 60 second
2021/12/03 13:24:01 [INFO] Get status connectors
2021/12/03 13:24:01 [INFO] Status connectors already
2021/12/03 13:24:01 [INFO] :|:Name:|:State_connector:|:State tasks:|:
2021/12/03 13:24:02 [INFO] ":|:objectmodel-connect:|:RUNNING:|:RUNNING:|:"
2021/12/03 13:24:02 [INFO] ":|:properties-connect:|:RUNNING:|:FAILED:|:"
* Closing connection -1
curl: (3) URL using bad/illegal format or missing URL

**Comment by sentoz** [comment]
Fixed starting with version 0.7.0
