### ISSUE TITLE
The bash script exits in the very beginning while logging the variable info

### ISSUE THREAD

**Issue by vmarora** [sentoz/kafka-connect-restart#5]
Repro steps - download the script file locally and try to run it. The script fails when running "log info SIDECAR_MODE="$SIDECAR_MODE"". 

To debug it, I enabled -x option in "set -euo pipefile" on line # 3 of the script. The script fails because the function log technically has a non zero code in the end when doing "[ "${lvl,,}" == success ]". Since -e option is set with "set -euo pipefail", the script exits. 

I have a fix for it by converting the line above to if condition. I will create a pull request for it.

**Comment by sentoz** [comment]
@vmarora Thank you.
