### ISSUE TITLE
Add ability to handle basic authentication

### ISSUE THREAD

**Issue by anvaari** [sentoz/kafka-connect-restart#7]
Hi dear Sentoz

I want to use this tool, but the Kafka connect I use seat behind Nginx and need basic authentication. 

I think It's easy to add this feature. we just need to use `curl -u username:password` instead of curl.

If you are ok I can work on it :)

**Comment by anvaari** [comment]
I also recommend to add option to ignore `PAUSED` connectors

**Comment by sentoz** [comment]
Greetings!) 

When the time comes, I will definitely add basic authorization, but I have nowhere to test.

**Comment by sentoz** [comment]
> I also recommend to add option to ignore `PAUSED` connectors

As for paused connectors, I don't check them, I only take failed.

**Comment by anvaari** [comment]
Thanks for fast reply :)

I will provide pull request for adding basic auth today

**Comment by anvaari** [comment]
for ignoring `PAUSED` connectors I open new issue. thanks
