### ISSUE TITLE
 Ignore `PAUSED` connectors when restart tasks

### ISSUE THREAD

**Issue by anvaari** [sentoz/kafka-connect-restart#8]
In Kafka connect cluster, some connectors maybe stopped (state=`PAUSED`). I think when we stop connector we don't need to restart it's task. 
in current `parse_failed_tasks` [func](https://github.com/sentoz/kafka-connect-restart/blob/645fae409e3a5cc7d15d5d67ef2c30afd8fde9f5/connector-restart#L73C1-L73C19) It restart all connectors which their task failed. But I think it shouldn't restart paused connectors.
I recommend to replace this with current `parse_failed_tasks` script:

```bash
parse_failed_tasks() {
  jq -erc -M '
    map({name: .status.name } + {tasks: .status.tasks} + {connector: .status.connector})
    | .[] | {task: ((.tasks[]) + {name: .name}), connector: .connector}
    | select(.task.state=="FAILED" and .connector.state != "PAUSED") |
    {name: .task.name, task_id: .task.id|tostring}
    | ("/connectors/"+ .name + "/tasks/" + .task_id + "/restart")
  '
}
```
I

**Comment by sentoz** [comment]
Thank you!)
